###################
ClinkTop:
###################
  PllConfig[:]: '85MHz'
  ###################
  Ch[0]:
    LinkMode: Full
    DataMode: 8Bit
    FrameMode: Line
    TapCount: 4
    DataEn: True
    Blowoff: False
    BaudRate: 9600 # units of bps
    SerThrottle: 10000 # (10ms x 1us throttle rate) = 10000
    SwControlValue: 0x0
    SwControlEn: 0x0
    HSkip: 0x0
    HActive: 0xFFFF
    VSkip: 0x0
    VActive: 0xFFFF
    ###################
    UartPiranha4: # Piranha4 UART interface
      SPF: '0'     # SFP: 0 = 8-bit mode
      CLM: '2'     # CLM: 2 = full
      SVM: '0'     # SVM: test pattern mode
      SEM: '0'     # SEM: Set Exposure Mode
      SET: '5000'  # SET: Set Exposure Time
      STM: '1'     # STM: External Trigger Mode
      SSF: '7000'
###################
TrigCtrl[0]:
  EnableTrig: True
  InvCC: False # Active High Pulse
  TrigMap: ChA
  TrigPulseWidth: 32.768 # units of us
  TrigMask: 0x1 # CC1 trigger
#########################################################################################################
