##################################################################################################
# 1944 (H) x 1472 (V)
# 2 Byte x 1944 x 1472 = 5723136 Byte Images
# 5723136 Byte Images x 120 Hz = 5.494 Gb/s
##################################################################################################
# https://www.imperx.com/cmos-cameras/c1921/
# https://www.imperx.com/download/335/spec-sheets/20491/cl_c1921_r2_2019_w.pdf
# https://www.imperx.com/wp-content/uploads/downloads/Cheetah_Pregius_CL_User_Manual_rev.1.3_f.pdf
##################################################################################################
ClinkTop:
###################
  PllConfig[:]: '50MHz'
  ###################
  Ch[0]:
    DataMode: 12Bit
    FrameMode: Frame
    #######################################
    TapCount: 2 # Base (2 taps or 3 taps)
    LinkMode: Base
    #######################################
    # TapCount: 4 # Medium (4 taps)
    # LinkMode: Medium
    #######################################
    # TapCount: 8 # Full (8 taps)
    # LinkMode: Full
    #######################################
    DataEn: True
    Blowoff: False
    BaudRate: 115200 # units of bps
    SerThrottle: 10000 # (30ms x 1us throttle rate) = 10000
    SwControlValue: 0x0
    SwControlEn: 0x0
    ###################
    UartImperxC1921: # Imperx C1921
      #######################################
      Trg_Mode_En: '1' # 0x1 - trigger is enabled; camera in trigger mode
      Trg_Inp_Sel: '3' # 0x3 - computer; camera expects trigger from CC1 via Camera Link cable.
      Trg_Edg_Sel: '0' # 0x0 - rising edge
      Trg_Dbn_Tim: '1' # Selects trigger signal de-bounce time in micro-seconds.
      Trg_Flt_Tim: '5' # Selects Filter time in micro-seconds. Any pulse shorter than the selected time is ignored.
      Trg_Ovr_Sel: '0' # 0x0 - ignore next trigger
      Trg_Mod_Sel: '1' # 0x1 - fast triggering
      Trg_Frm_Cap: '1' # Selects number of frames captured after each trigger signal
      Trg_Exp_Del: '1' # Selects delay in microseconds between trigger signal and beginning of exposure
      Trg_Str_En:  '0' # 0x0 - disable Trigger Strobe
      #######################################
      A2D_Bits:    '2' # 0x2 - 12 bits
      Bit_Dpt_Sel: '2' # 0x2 - 12 bits
      Exp_Ctl_Mod: '1' # 0x1 - pulse width - for triggering
      #######################################
      Dat_Fmt_Sel: '0' # 0x0 - Base (2 taps)
      # Dat_Fmt_Sel: '1' # 0x1 - Base (3 taps)
      # Dat_Fmt_Sel: '2' # 0x2 - Medium (4 taps)
      # Dat_Fmt_Sel: '3' # 0x3 - Full (8 taps)
      #######################################
###################
TrigCtrl[0]:
  EnableTrig: True
  InvCC: False # Active High Pulse
  TrigMap: ChA # ChA = pgpTrigger(0)
  TrigPulseWidth: 32.768 # units of us
  TrigMask: 0x1 # CC1 trigger
###################
